### PR TITLE
Update L1 + L2 clubs' details

### PR DESCRIPTION
**Pull request by mbilbille**
Complete base information with code, city and full name.

### CODE REVIEW

**Comment by geraldb** [comment]
Merci. Great. Thanks. Cheers.

**Comment by geraldb** [comment]
@mbilbille FYI: You're invited to join the editors team for fr-france (with commit rights) you can change all files directly (without a pull request etc.). Cheers.

**Comment by mbilbille** [comment]
Thx, I'll try update matches as well.

**Comment by geraldb** [comment]
Thanks. No rush. Take your time. Will try to get the data online and a booklet (auto-)generated in the next weeks. Cheers.

**Comment by mbilbille** [comment]
@geraldb I got the following error, on a `git push upstream master`:
> remote: Permission to openfootball/fr-france.git denied to mbilbille.
fatal: unable to access 'https://github.com/openfootball/fr-france.git/': The requested URL returned error: 403

**Comment by mbilbille** [comment]
My bad! I didn't check my mailbox :)

**Comment by geraldb** [comment]
Sorry for the confusion. GitHub will send you an invitation by email that you need to accept (e.g. click on the link - it's a github procedure to make sure you will not get added to a team you do not want). No worries. Cheers.

**Pull request merged**
